[package]
name = "example_app"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_spacetimedb = { path = "../bevy_spacetimedb" }
bevy = { workspace = true }
spacetimedb-sdk = { workspace = true }
